Best trial:
  Value:  12.0
  Model: a2c
  Params: 
    gamma: 0.95
    normalize_advantage: True
    max_grad_norm: 0.6
    use_rms_prop: True
    gae_lambda: 0.99
    n_steps: 256
    lr_schedule: constant
    learning_rate: 0.011990568639893203
    ent_coef: 0.0001762335127850959
    vf_coef: 0.15658994629928458
    ortho_init: True
    net_arch: small
    activation_fn: tanh